import { ObjectId } from "mongodb";
import { PlantData } from "../graphql/graphql";

export type TypeConflictDataKeys =
  | "occurrenceCoords"
  | "mediaUrls"
  | "occurrenceIds"
  | "scrapeSources";

export type PlantDataArrays = Pick<PartialPlantData, TypeConflictDataKeys>;

// Omitting and redefining keys from TypeConflictDataKeys due to tsoa bug resolving 'Maybe<...>' types.
// 'Maybe<...>' types are auto-generated by the graphql codegen for optional fields.
export type PlantDataDocument = Omit<PlantData, TypeConflictDataKeys> & {
  _id?: ObjectId;

  otherTraits?: Record<string, string>;
  occurrenceCoords?: number[][];
  mediaUrls?: string[];

  scrapeSources?: string[];
  occurrenceIds?: number[];
};

export type PartialPlantData = Omit<
  PlantDataDocument,
  "addedTimestamp" | "updatedTimestamp"
>;

/**
 * @property count: Count of results, which is new/unique occurrences found
 * @property results: The unique occurrences found (omits mongodb timestamp information)
 * @property totalOccurrencesScraped: The total (non-unique) occurrences found
 * @property endOfRecords: Direct property from GBIF response, whether there are more occurrences
 *   via this search
 */
export type OccurrenceScrapeResponse = {
  count: number;
  results: PartialPlantData[];

  totalOccurrencesScraped: number;
  endOfRecords: boolean;
};
