/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/species-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List plant species */
        get: {
            parameters: {
                query: {
                    key: string;
                    page?: number;
                    q?: string;
                    edible?: boolean;
                    poisonous?: boolean;
                    cycle?: "perennial" | "annual" | "biennial" | "biannual";
                    watering?: string;
                    sunlight?: string;
                    indoor?: boolean;
                    hardiness?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A paginated list of species */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SpeciesListItem"][];
                            pagination?: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/details/{species_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get detailed info for a species */
        get: {
            parameters: {
                query: {
                    key: string;
                };
                header?: never;
                path: {
                    species_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed species info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpeciesDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species-care-guide-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get care guides for a species */
        get: {
            parameters: {
                query: {
                    key: string;
                    species_id: number;
                    page?: number;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of care guides */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hardiness-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hardiness zone map for a species */
        get: {
            parameters: {
                query: {
                    key: string;
                    species_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hardiness map data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pest-disease-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pest/disease list */
        get: {
            parameters: {
                query: {
                    key: string;
                    page?: number;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of pests and diseases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SpeciesListItem: {
            id?: number;
            common_name?: string;
            scientific_name?: string;
            cycle?: string;
            sunlight?: string;
        };
        Pagination: {
            current_page?: number;
            total_pages?: number;
            total?: number;
        };
        SpeciesDetail: {
            id?: number;
            common_name?: string;
            scientific_name?: string;
            edible?: boolean;
            poisonous?: boolean;
            watering?: string;
            sunlight?: string;
            dimensions?: {
                min_height_cm?: number;
                max_height_cm?: number;
                spread_cm?: number;
            };
            flowering_season?: string[];
            flower_color?: string[];
            foliage_color?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
